/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticiRouteImport } from './routes/statistici'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BoostRouteImport } from './routes/boost'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerIdRouteImport } from './routes/server.$id'

const StatisticiRoute = StatisticiRouteImport.update({
  id: '/statistici',
  path: '/statistici',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostRoute = BoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerIdRoute = ServerIdRouteImport.update({
  id: '/server/$id',
  path: '/server/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/boost': typeof BoostRoute
  '/dashboard': typeof DashboardRoute
  '/packages': typeof PackagesRoute
  '/servers': typeof ServersRoute
  '/statistici': typeof StatisticiRoute
  '/server/$id': typeof ServerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/boost': typeof BoostRoute
  '/dashboard': typeof DashboardRoute
  '/packages': typeof PackagesRoute
  '/servers': typeof ServersRoute
  '/statistici': typeof StatisticiRoute
  '/server/$id': typeof ServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/boost': typeof BoostRoute
  '/dashboard': typeof DashboardRoute
  '/packages': typeof PackagesRoute
  '/servers': typeof ServersRoute
  '/statistici': typeof StatisticiRoute
  '/server/$id': typeof ServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/boost'
    | '/dashboard'
    | '/packages'
    | '/servers'
    | '/statistici'
    | '/server/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/boost'
    | '/dashboard'
    | '/packages'
    | '/servers'
    | '/statistici'
    | '/server/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/boost'
    | '/dashboard'
    | '/packages'
    | '/servers'
    | '/statistici'
    | '/server/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BoostRoute: typeof BoostRoute
  DashboardRoute: typeof DashboardRoute
  PackagesRoute: typeof PackagesRoute
  ServersRoute: typeof ServersRoute
  StatisticiRoute: typeof StatisticiRoute
  ServerIdRoute: typeof ServerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistici': {
      id: '/statistici'
      path: '/statistici'
      fullPath: '/statistici'
      preLoaderRoute: typeof StatisticiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost': {
      id: '/boost'
      path: '/boost'
      fullPath: '/boost'
      preLoaderRoute: typeof BoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$id': {
      id: '/server/$id'
      path: '/server/$id'
      fullPath: '/server/$id'
      preLoaderRoute: typeof ServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BoostRoute: BoostRoute,
  DashboardRoute: DashboardRoute,
  PackagesRoute: PackagesRoute,
  ServersRoute: ServersRoute,
  StatisticiRoute: StatisticiRoute,
  ServerIdRoute: ServerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
